
'''
	Created by Nick Hartley
	12/11/2017
'''

class Links:
	profile = '//div[@id="usernav_client_info"]/ul/li[2]/a'
	my_profile = '//div[@id="usernav_client_info"]/ul/li[2]/ul/li/a'
	download_center = '//div[@id="usernav_client_info"]/ul/li[2]/ul/li/a[3]'
	logout = '//div[@id="usernav_client_info"]/ul/li[2]/ul/li/a[4]'
	customer_numbers = '//div[@id="quicksearch_config_div"]/ul/li[2]/a'
	customer_custom_ids = '//div[@id="quicksearch_config_div"]/ul/li[3]/a'
	customer_names = '//div[@id="quicksearch_config_div"]/ul/li[4]/a'
	customer_addresses = '//div[@id="quicksearch_config_div"]/ul/li[5]/a'
	job_numbers = '//div[@id="quicksearch_config_div"]/ul/li[6]/a'
	job_names = '//div[@id="quicksearch_config_div"]/ul/li[7]/a'
	full_wildcard_search = '//div[@id="quicksearch_config_div"]/ul/li[9]/a'
	mark_billto_shipto = '//div[@id="quicksearch_config_div"]/ul/li[11]/a'
	dashboard = '//div[@id="menu_container"]/ul/li/a'
	search = '//div[@id="menu_container"]/ul/li[2]/a'
	customer_search = '//div[@id="menu_container"]/ul/li[2]/ul/li/a'
	document_search = '//div[@id="menu_container"]/ul/li[2]/ul/li[2]/a'
	job_search = '//div[@id="menu_container"]/ul/li[2]/ul/li[3]/a'
	saved_searches = '//div[@id="menu_container"]/ul/li[2]/ul/li[4]/a'
	customers = '//div[@id="menu_container"]/ul/li[3]/a'
	add_customer = '//div[@id="menu_container"]/ul/li[3]/ul/li/a'
	add_job = '//div[@id="menu_container"]/ul/li[3]/ul/li[2]/a'
	bulk_import = '//div[@id="menu_container"]/ul/li[3]/ul/li[3]/a'
	bulk_delete = '//div[@id="menu_container"]/ul/li[3]/ul/li[4]/a'
	same_as_editor = '//div[@id="menu_container"]/ul/li[3]/ul/li[5]/a'
	manage_documents = '//div[@id="menu_container"]/ul/li[4]/a'
	validate_documents = '//div[@id="menu_container"]/ul/li[4]/ul/li/a'
	all_companies = '//div[@id="menu_container"]/ul/li[4]/ul/li[2]/a'
	send_single_request = '//div[@id="menu_container"]/ul/li[4]/ul/li[3]/a'
	campaigns = '//div[@id="menu_container"]/ul/li[4]/ul/li[4]/a'
	email_templates_and_cover_letters = '//div[@id="menu_container"]/ul/li[4]/ul/li[5]/a'
	content_library = '//div[@id="menu_container"]/ul/li[5]/a'
	document_library = '//div[@id="menu_container"]/ul/li[5]/ul/li/a'
	nexus_settings = '//div[@id="menu_container"]/ul/li[5]/ul/li[2]/a'
	exemption_matrix = '//div[@id="menu_container"]/ul/li[5]/ul/li[3]/a'
	reports = '//div[@id="menu_container"]/ul/li[6]/a'
	document_reports = '//div[@id="menu_container"]/ul/li[6]/ul/li/a'
	customer_reports = '//div[@id="menu_container"]/ul/li[6]/ul/li[2]/a'
	logistic_reports = '//div[@id="menu_container"]/ul/li[6]/ul/li[3]/a'
	user_reports = '//div[@id="menu_container"]/ul/li[6]/ul/li[4]/a'
	settings = '//div[@id="menu_container"]/ul/li[7]/a'
	sysadmin = '//div[@id="menu_container"]/ul/li[7]/ul/li[1]/a' #issue - DUPLICATE position changes with account type
	account_settings = '//div[@id="menu_container"]/ul/li[7]/ul/li/a'
	account_details = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li/a'
	exposure_zones = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[2]/a'
	exposure_zone_attributes = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[3]/a'
	invalid_reasons = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[4]/a'
	document_categories = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[5]/a'
	document_attributes = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[6]/a'
	customer_attributes = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[7]/a'
	manage_users = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[8]/a'
	user_roles = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[9]/a'
	notification_subscriptions = '//div[@id="menu_container"]/ul/li[7]/ul/li/ul/li[10]/a'
	company_settings = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/a'
	company_details = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li/a'
	company_same_as = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[2]/a'
	custom_fields = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[3]/a'
	assign_users = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[4]/a'
	data_entry_sets = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[5]/a'
	locations = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[6]/a'
	buckets = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[7]/a'
	public_wizard = '//div[@id="menu_container"]/ul/li[7]/ul/li[2]/ul/li[8]/a'
	retail = '//div[@id="menu_container"]/ul/li[8]/a'

	
class Buttons:
	doc_type_button = '//span[@id="doctype-dropdown"]/button'
	company_dropdown_button = '//span[@id="division-dropdown"]/button'
	account_dropdown_button = '//span[@id="company-dropdown"]/button'
	quick_search_button = '//div[@id="qsearch"]/button'
	quick_search_config_button = '//div[@id="quicksearch_config_div"]/button'
	add_widgets = '//div[@id="content"]/button'
	insights = '//div[@id="content"]/button[2]'
	manage_dashboard_close = '//div[@id="manage_dashboard"]/div/div/div/button'
	manage_dashboard_done = '//div[@id="manage_dashboard"]/div/div/div[3]/button'	
	
	
	
	
	