
__author__ = 'Nick Hartley'
# 3/9/2018


class Links:
    united_states = '//*[@id="acc_tab"]/li[1]/a'
    canada = '//*[@id="acc_tab"]/li[2]/a'
    other = '//*[@id="acc_tab"]/li[3]/a'


class Buttons:
    assign_nexus = '//*[@id="edit_client_nexus_btn"]'
    us_edit_client_nexus_modal_close = '//*[@id="edit_client_nexus_modal"]/div/div/div[1]/button'
    us_edit_client_nexus_modal_cancel = '//*[@id="edit_client_nexus_modal"]/div/div/div[3]/button[2]'
    us_edit_client_nexus_modal_update_client_nexus = '//*[@id="edit_client_nexus"]'
    canada_edit_client_nexus_modal_close = '//*[@id="edit_client_nexus_modal"]/div/div/div[1]/button'
    canada_edit_client_nexus_modal_cancel = '//*[@id="edit_client_nexus_modal"]/div/div/div[3]/button[2]'
    canada_edit_client_nexus_modal_update_client_nexus = '//*[@id="edit_client_nexus"]'
    other_edit_client_nexus_modal_close = '//*[@id="edit_client_nexus_modal"]/div/div/div[1]/button'
    other_edit_client_nexus_modal_cancel = '//*[@id="edit_client_nexus_modal"]/div/div/div[3]/button[2]'
    other_edit_client_nexus_modal_update_client_nexus = '//*[@id="edit_client_nexus"]'
    success_modal_ok = '//*[@id="success_prompt_dialog"]/div/div/div[3]/button'
    success_modal_x = '//*[@id="success_prompt_dialog"]/div/div/div[1]/button'


class Inputs:
    us_edit_client_nexus_modal_toggle_select_all = '//form[@id="edit_nexus_form"]/table/tbody/tr/td/input'
    us_edit_client_nexus_modal_alaska = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr/td[2]/input'
    us_edit_client_nexus_modal_alabama = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[2]/td[2]/input'
    us_edit_client_nexus_modal_arkansas = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[3]/td[2]/input'
    us_edit_client_nexus_modal_american_samoa = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[4]/td[2]/input'
    us_edit_client_nexus_modal_arizona = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[5]/td[2]/input'
    us_edit_client_nexus_modal_california = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[6]/td[2]/input'
    us_edit_client_nexus_modal_colorado = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[7]/td[2]/input'
    us_edit_client_nexus_modal_connecticut = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[8]/td[2]/input'
    us_edit_client_nexus_modal_district_of_columbia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[9]/td[2]/input'
    us_edit_client_nexus_modal_delaware = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[10]/td[2]/input'
    us_edit_client_nexus_modal_florida = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[11]/td[2]/input'
    us_edit_client_nexus_modal_georgia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[12]/td[2]/input'
    us_edit_client_nexus_modal_guam = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[13]/td[2]/input'
    us_edit_client_nexus_modal_hawaii = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[14]/td[2]/input'
    us_edit_client_nexus_modal_iowa = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[15]/td[2]/input'
    us_edit_client_nexus_modal_idaho = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[16]/td[2]/input'
    us_edit_client_nexus_modal_illinois = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[17]/td[2]/input'
    us_edit_client_nexus_modal_indiana = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[18]/td[2]/input'
    us_edit_client_nexus_modal_kansas = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[19]/td[2]/input'
    us_edit_client_nexus_modal_kentucky = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[20]/td[2]/input'
    us_edit_client_nexus_modal_louisiana = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[21]/td[2]/input'
    us_edit_client_nexus_modal_massachusetts = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[22]/td[2]/input'
    us_edit_client_nexus_modal_maryland = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[23]/td[2]/input'
    us_edit_client_nexus_modal_maine = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[24]/td[2]/input'
    us_edit_client_nexus_modal_michigan = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[25]/td[2]/input'
    us_edit_client_nexus_modal_minnesota = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[26]/td[2]/input'
    us_edit_client_nexus_modal_missouri = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[27]/td[2]/input'
    us_edit_client_nexus_modal_northern_mariana_islands = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[28]/td[2]/input'
    us_edit_client_nexus_modal_mississippi = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr/td[2]/input'
    us_edit_client_nexus_modal_montana = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[2]/td[2]/input'
    us_edit_client_nexus_modal_north_carolina = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[3]/td[2]/input'
    us_edit_client_nexus_modal_north_dakota = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[4]/td[2]/input'
    us_edit_client_nexus_modal_nebraska = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[5]/td[2]/input'
    us_edit_client_nexus_modal_new_hampshire = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[6]/td[2]/input'
    us_edit_client_nexus_modal_new_jersey = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[7]/td[2]/input'
    us_edit_client_nexus_modal_new_mexico = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[8]/td[2]/input'
    us_edit_client_nexus_modal_nevada = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[9]/td[2]/input'
    us_edit_client_nexus_modal_new_york = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[10]/td[2]/input'
    us_edit_client_nexus_modal_ohio = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[11]/td[2]/input'
    us_edit_client_nexus_modal_oklahoma = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[12]/td[2]/input'
    us_edit_client_nexus_modal_oregon = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[13]/td[2]/input'
    us_edit_client_nexus_modal_pennsylvania = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[14]/td[2]/input'
    us_edit_client_nexus_modal_puerto_rico = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[15]/td[2]/input'
    us_edit_client_nexus_modal_rhode_island = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[16]/td[2]/input'
    us_edit_client_nexus_modal_south_carolina = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[17]/td[2]/input'
    us_edit_client_nexus_modal_south_dakota = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[18]/td[2]/input'
    us_edit_client_nexus_modal_tennessee = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[19]/td[2]/input'
    us_edit_client_nexus_modal_texas = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[20]/td[2]/input'
    us_edit_client_nexus_modal_utah = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[21]/td[2]/input'
    us_edit_client_nexus_modal_virginia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[22]/td[2]/input'
    us_edit_client_nexus_modal_vermont = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[23]/td[2]/input'
    us_edit_client_nexus_modal_washington = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[24]/td[2]/input'
    us_edit_client_nexus_modal_wisconsin = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[25]/td[2]/input'
    us_edit_client_nexus_modal_west_virginia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[26]/td[2]/input'
    us_edit_client_nexus_modal_wyoming = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[27]/td[2]/input'
    us_edit_client_nexus_modal_us_virgin_islands = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[28]/td[2]/input'
    canada_edit_client_nexus_modal_toggle_select_all = '//form[@id="edit_nexus_form"]/table/tbody/tr/td/input'
    canada_edit_client_nexus_modal_alberta = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr/td[2]/input'
    canada_edit_client_nexus_modal_british_columbia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[2]/td[2]/input'
    canada_edit_client_nexus_modal_manitoba = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[3]/td[2]/input'
    canada_edit_client_nexus_modal_new_brunswick = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[4]/td[2]/input'
    canada_edit_client_nexus_modal_newfoundland = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[5]/td[2]/input'
    canada_edit_client_nexus_modal_nova_scotia = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[6]/td[2]/input'
    canada_edit_client_nexus_modal_northwest = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td/table/tbody/tr[7]/td[2]/input'
    canada_edit_client_nexus_modal_nunavat = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr/td[2]/input'
    canada_edit_client_nexus_modal_ontario = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[2]/td[2]/input'
    canada_edit_client_nexus_modal_prince_edwards_island = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[3]/td[2]/input'
    canada_edit_client_nexus_modal_quebec = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[4]/td[2]/input'
    canada_edit_client_nexus_modal_saskatchewan = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[5]/td[2]/input'
    canada_edit_client_nexus_modal_yukon = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[6]/td[2]/input'
    canada_edit_client_nexus_modal_canadian_federal = '//form[@id="edit_nexus_form"]/table[2]/tbody/tr/td[2]/table/tbody/tr[7]/td[2]/input'
    other_edit_client_nexus_modal_toggle_select_all = '//*[@id="toggle_zones_other"]'
